### ISSUE TITLE
applyCss warning in Angular 9.1

### ISSUE THREAD

**Issue by alexcoroza** [czeckd/angular-svg-icon#102]
In my code I am using 
`<svg-icon *ngIf="gameDate" class="arrow-icon" src="{{ environment.iconPath }}chevron-left.svg" [applyCss]="true" (click)="selectPrevDate()"></svg-icon>`

But just today I tried to upgrade my project into Angular 9. I think it was successful except there are lots of warning that appeared in my Chrome console saying `applyCss deprecated since 9.1.0, will be removed in 10.0.0` and `use applyClass instead`. Of course I tried `applyClass` but its not supported by angular-svg-icon. Im using version 9.2.0

**Comment by czeckd** [comment]
Are you absolutely certain you're using 9.2.0? Because `[applyClass]="true"` is working in this [stackblitz](https://stackblitz.com/edit/angular-ivy-8bs7fq?file=src%2Fapp%2Fapp.component.html) I just made.
