### ISSUE TITLE
Support for angular 10?

### ISSUE THREAD

**Issue by Rene4100** [czeckd/angular-svg-icon#104]
Any plans for a release that supports angular 10? :)

**Comment by czeckd** [comment]
Is v9.2.0 not working with ng10?

**Comment by Rene4100** [comment]
> 
> 
> Is v9.2.0 not working with ng10?

I previously had some problems upgrading as angular-svg-icon@9.2.0 requires tslib@^1.10.0 which in ng10 have been upgraded to ^2.0.0.
Thanks for the help 👍

**Comment by czeckd** [comment]
Thanks! Version 10.0.0 should now be available from npm.
