### ISSUE TITLE
ERROR TypeError: Cannot read property 'add' of undefined

### ISSUE THREAD

**Issue by jhornancolina** [czeckd/angular-svg-icon#107]
`
ERROR TypeError: Cannot read property 'add' of undefined
    at DefaultDomRenderer2.addClass (platform-browser.js:1238)
    at BaseAnimationRenderer.addClass (animations.js:613)
    at SvgIconComponent.setClass (angular-svg-icon.js:329)
    at SvgIconComponent.ngOnChanges (angular-svg-icon.js:174)
    at SvgIconComponent.wrapOnChangesHook_inPreviousChangesStorage (core.js:27058)
    at callHook (core.js:4712)
    at callHooks (core.js:4672)
    at executeInitAndCheckHooks (core.js:4612)
    at selectIndexInternal (core.js:9661)
    at Module.ɵɵadvance (core.js:9622)`

**This is code where I have the <svg-icon>**

```
<svg-icon
        [svgClass]="'svg-icon'"
        src="assets/images/user/dashboard-white.svg"
        viewBox="0 0 400 400"
      >
        ></svg-icon
      >
```

**This is my module**
```
import { DlmRoutingModule } from './dlm.router.module';
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { DlmInformationComponent } from './information/dlm-information.component';
import { PanelComponent } from './panel/panel.component';
import { AngularSvgIconModule } from 'angular-svg-icon';
@NgModule({
  declarations: [DlmInformationComponent, PanelComponent],
  imports: [CommonModule, DlmRoutingModule, AngularSvgIconModule.forRoot()],
})
export class DlmModule {}
```

**Comment by czeckd** [comment]
I have not been able to reproduce this with my sample SVGs. Could you please provide the SVG that is causing this error? 

Also, what version of angular-svg-icon are you using and what version of Angular? Thanks.

**Comment by jhornancolina** [comment]
Thanks for your reply. I currently using angular 8.

link of the svg
`` 
https://mega.nz/file/BZoGiYya#vMueZ_X6H_cNIrXrQmkccd-83wj5n3UyrZA_EG2DIx4
``

**Comment by czeckd** [comment]
It looks like you have a stray `>` in your template syntax that causes the error. If you remove the extra `>`, then the svg loads without error. This mark-up worked for me:
```
<svg-icon
  [svgClass]="'svg-icon'"
  src="assets/images/user/dashboard-white.svg"
   viewBox="0 0 400 400"
>
</svg-icon>
```

**Comment by jhornancolina** [comment]
Omg, thanks for your reply it works. Sorry for reply you too late I had a
lot of work. Thanks you a lot bro!
