### ISSUE TITLE
Upgrade from 8.0.0 to 10.0.0 applyCss to applyClass broken

### ISSUE THREAD

**Issue by coonmoo** [czeckd/angular-svg-icon#110]
We just upgraded from 8.0.0 to 10.0.0 and replaced all applyCss calls with applyClass.

`public userColor:string = 'red';`

`<svg-icon [class]="userColor" [src]="'./images/colors/'+userColor+'.svg'" [applyClass]="true"></svg-icon>
`

Result is now:
`<svg-icon _ngcontent-ctn-c172="" ng-reflect-src="./images/colors/red" ng-reflect-apply-css="true"><svg ....
`
Previous with 8.0.0 and applyCss it was
`<svg-icon _ngcontent-ctn-c172="" class="red" ng-reflect-src="./images/colors/red" ng-reflect-apply-css="true"><svg ....
`

Any ideas on that? Thank you

**Comment by czeckd** [comment]
It seems to me you have a partially built app with the older version. Try rebuilding completely and/or removing your cached node_modules and then rerunning npm install and then rebuilding.
