### ISSUE TITLE
'svg-icon' is not a known element:

### ISSUE THREAD

**Issue by ccocker** [czeckd/angular-svg-icon#116]
I have installed this package on angular v11.09 and get an error saying it is not an angular component.

**App Module**
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { HttpClientModule } from '@angular/common/http';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AngularSvgIconModule } from 'angular-svg-icon';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    HttpClientModule,
    AngularSvgIconModule.forRoot(),
  ],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}

```
Component
`<svg-icon src="miProject/assets/icons/icon_home.svg" ></svg-icon>`

**Comment by czeckd** [comment]
I am unable to replicate the error you are seeing with `ng-version="11.0.9"` in a basic hello world type project.

Is this the error that you are seeing?
```
error NG8001: 'svg-icon' is not a known element:
    1. If 'svg-icon' is an Angular component, then verify that it is part of this module.
```

Are you using the svg-icon in a component in a sub-module? Did you import the package in the sub-module too? Like so:
```ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { QuickTestComponent } from './quick-test/quick-test.component';
import { HttpClientModule } from '@angular/common/http';
import { AngularSvgIconModule } from 'angular-svg-icon';

@NgModule({
  declarations: [ QuickTestComponent ],
  imports: [
    CommonModule,
    AngularSvgIconModule
  ],
  exports: [ QuickTestComponent ]
})
export class QuickTestModule { }
```

**Comment by ccocker** [comment]
You are absolutely correct, i missed that in the documentation.  It works beautifully.  Very Cool Package, very flexible - thank you.

Issue can be closed.

**Comment by midlantica** [comment]
I've tried all the advice... still not working.. Angular 13, very simple setup, followed above.. tried with AngularSvgIconModule.forRoot() and without forRoot().. Pls tell me what top do! 
![image](https://user-images.githubusercontent.com/1449595/174859017-2c013f98-2c89-4e87-88bf-fb49ad06df16.png)

**Comment by czeckd** [comment]
@midlantica - Can you share your source? I don't have a guess what the issue is.
