### ISSUE TITLE
input [class] only accepts one class

### ISSUE THREAD

**Issue by MickL** [czeckd/angular-svg-icon#122]
If I see it right then `[class]` only accepts one string input but not multiple classes. For example the following is not working:

```
<svg-icon src="assets/icons/arrow.svg" [class]="'icon icon-large'"></svg-icon>
```

I would love to see `<svg-icon>` to either accept `string` with multiple classes, as shown above, OR accept `string | string[]`.

**Comment by czeckd** [comment]
@MickL — just to confirm, this is not working for you in v11.1.2?

**Comment by czeckd** [comment]
I made some changes that should help with `string[]` in angular-svg-icon@11.2.0. Please let me know if that takes care of your issue.
