### ISSUE TITLE
Register SVG from CDN

### ISSUE THREAD

**Issue by cartifon** [czeckd/angular-svg-icon#128]
Hi guys. 

I have a project where I can't have any assets on it, so my assets are in a CDN, and I would like to register my SVG icons using the CDN URL, but it does not accept to get from a CDN.... How would I do that? 

I am using the version "angular-svg-icon": "~9.2.0". 

I tried to add the icons using sanitize, and it didn't work, this is what I did:

```
const svgIcons = [
     ...
    {
        iconName: 'footer-logo',
        iconPath: `https://dx9457ojp328v.cloudfront.net/icons/footer-logo.svg`,
    }
    ...
];

private registerSvgIcons(): void {
    svgIcons.forEach((icon) => {
      const trustedUrl = this.domSanitizer.sanitize(SecurityContext.RESOURCE_URL, this.domSanitizer.bypassSecurityTrustResourceUrl(icon.iconPath)) as string;
      this.svgRegistry.loadSvg(icon.iconPath, icon.iconName);
    });
  }
```

Any idea on how to register SVG from CDN?

**Comment by czeckd** [comment]
It looks like this is a typo from your example:
```ts
      this.svgRegistry.loadSvg(icon.iconPath, icon.iconName);
```
and, you probably meant to do:
```ts
      this.svgRegistry.loadSvg(trustedUrl, icon.iconName);
```
but, in theory that should work.

Is the SVG fetch being blocked by the browser's CORS policy? Are you seeing something like this in the console:
```
Access to XMLHttpRequest at 'https://dx9457ojp328v.cloudfront.net/icons/footer-logo.svg' 
from origin 'http://localhost:4200' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
Or something else?

**Comment by cartifon** [comment]
Thanks for the super fast answer @czeckd, sorry about the typo, I meant to paste the code where the trustedUrl, but even with that it does not work.

In the console, when I pass the trustedUrl I get this error: 
![image](https://user-images.githubusercontent.com/7103578/115446870-cfc04880-a1e5-11eb-8681-1af6c5b865ab.png)

and for the CORS policy, I didn't get any error like that, I can use the CDN url as a src for images...

**Comment by czeckd** [comment]
Yes, I get a similar error after the CORS failure using a trusted URL or not.

For example, when I substitute your CDN's SVG URL with a URL of a SVG from wikimedia.org, such as
`https://upload.wikimedia.org/wikipedia/commons/e/e6/Elephant-2.svg`, the load works.

Please look in the Network tab and see what the status of the GET on the footer-logo.svg is. My hunch is it is a CORS error.

**Comment by cartifon** [comment]
Thanks, yes, it does get the CORS on the network... That's why it is a Unknown Error I think... Thanks man, I will double check the server for the SVGs.
