### ISSUE TITLE
Styling <svg-icon> element impossible?

### ISSUE THREAD

**Issue by Voxen** [czeckd/angular-svg-icon#130]
Appyling CSS styles on the `<svg-icon>` element doesn't seem to work.

In my app I do something like:

HTML:
```
<div class="container">
  <svg-icon class="icon" name="test"></svg-icon>
</div>
```

CSS:
```
div.container {
  width: 24px;
  height: 8px;
}

.icon {
  width: 100%;
  height: 100%;
}
```

But at runtime the `<svg-icon>` element gets a size of 24 x 17 instead of 24 x 8.
Using chrome dev tools I can see that nothing overrides the CSS settings, so I don't understand why the element don't get the style I apply to it.

**Comment by czeckd** [comment]
@Voxen 
What version of Angular and angular-svg-icon are you using?
Did you try apply the width and height directly using `svgStyle`? Did you try applying the style directly using `svgClass`? Did you try using `stretch` on the svg?
Can you post the svg? Or, confirm it does not have a width and height set on it?

**Comment by Voxen** [comment]
Thanks for your reply.
Meantime I was able to set the size adding "display:block" to the .icon class.
