### ISSUE TITLE
ERROR No svg with name 'xxxx' has been loaded with Angular SSR

### ISSUE THREAD

**Issue by RRGT19** [czeckd/angular-svg-icon#131]
Angular CLI: 11.2.10
Node: 14.15.5
OS: darwin x64
Angular: 11.2.11
Ivy Workspace: Yes
--------

I'm using the [angular-svg-icon-preloader](https://github.com/pjlamb12/angular-svg-icon-preloader) to load my icons.
I have read and followed the "[Usage with Angular Universal](https://github.com/czeckd/angular-svg-icon#usage-with-angular-universal)" to make it work with SSR. I followed and copy the implementation on the [demo-universal-angular-svg-loader](https://github.com/edulelis/demo-universal-angular-svg-loader). It's working and the icons are showing up, but, when my server starts to receive requests, I get these errors in the console:

```
An error occurred loading the icons:
 NetworkError
    at XMLHttpRequest.send (/webapp/dist/web-app/server/main.js:102530:19)
    at Observable._subscribe (/webapp/dist/web-app/server/main.js:188462:17)
No icons will be loaded.

ERROR No svg with name 'xxxxx' has been loaded
```

Maybe there is an issue with the [angular-svg-icon-preloader](https://github.com/pjlamb12/angular-svg-icon-preloader) and SSR?

When I open my App using SSR, I see these requests:
![Image](https://i.ibb.co/LrRt8CR/Screen-Shot-2021-07-23-at-2-16-00-PM.png)

Notice that there is one request to load my icons.json file and then, all my .svg files. This is normal? I don't know what is the cause of my errors in console.

**Comment by czeckd** [comment]
It might be better to redirect this issue to [angular-svg-icon-preloader](https://github.com/pjlamb12/angular-svg-icon-preloader) project and ask about how it works with SSR.

**Comment by RRGT19** [comment]
> It might be better to redirect this issue to [angular-svg-icon-preloader](https://github.com/pjlamb12/angular-svg-icon-preloader) project and ask about how it works with SSR.

I have posted the issue there, didn't know how to redirect or place the issue there without copy/paste the description. I think we can close or delete this post to avoid confusion and duplicates.
