### ISSUE TITLE
Empty classes being added cause a crash

### ISSUE THREAD

**Issue by icorne** [czeckd/angular-svg-icon#133]
if you add a whitespace too much in your classes you want added, you'll get a crash

https://github.com/czeckd/angular-svg-icon/blob/1790114e5f1b0173e0741212d3fb2d5e350b3822/projects/angular-svg-icon/src/lib/svg-icon.component.ts#L269

Should check for any empty classes

**Comment by czeckd** [comment]
@icorne : I'll update this issue when I get a release built with this fix. Thank you!

**Comment by czeckd** [comment]
Released in v13.0.0.
