### ISSUE TITLE
How to bind click event to the element in SVG

### ISSUE THREAD

**Issue by lhf552004** [czeckd/angular-svg-icon#137]
Hi I tried to get the svg element by elementRef.
`@ViewChild('container', {read: ElementRef}) containerElement: ElementRef;`
And in the html:
`<svg-icon #container [src]="'assets/svgs/'+ line.name + '.svg'" [stretch]="true" [viewBox]="'auto'"></svg-icon>`
However, I could not get svg by the following code
```
  ngAfterViewInit(): void {
    const svg = this.containerElement.nativeElement.querySelector('svg');
    if (svg) {
      console.log(svg.contentWindow);
    }
    // cw.openStorage = this.openStorage.bind(this);
  }
```
When debugging, I found the children's count is 0 for the native element (svg-icon)
Could you give me some suggestions?
Thanks.

**Comment by czeckd** [comment]
I would do it like this:

```html
<svg-icon src="assets/images/test.svg" (click)="onClick($event)"></svg-icon>
```

```ts
  onClick(event: Event): void {
    console.log(event);
  }
```

**Comment by lhf552004** [comment]
@czeckd Thanks, it works. But can I access the element when initialize? I mean in the ngOnInit or ngOnChanges, how can I initialize or update the status of the elements?

**Comment by czeckd** [comment]
I do not understand what you're trying to do, since with Angular you wouldn't be manipulating the DOM so directly. But if you need to access the loaded SVG, then you could do something like this:

```ts
import { AfterViewInit, Component, ElementRef, QueryList, ViewChildren } from '@angular/core';
import { SvgIconComponent } from 'angular-svg-icon';

@Component({
  selector: 'app-testbed',
  templateUrl: './testbed.component.html',
  styleUrls: ['./testbed.component.scss']
})
export class TestbedComponent implements AfterViewInit {
  @ViewChildren(SvgIconComponent, { read: ElementRef }) svgIcons!: QueryList<ElementRef>;

  ngAfterViewInit(): void {
    setTimeout( () => {
      // Read the first svg, if any.
      const icn = this.svgIcons.get(0);
      if (icn) {
        const svg = icn.nativeElement.firstChild;
        console.log(svg);
      }
    }, 250);  // An estimate of the time it takes for the svg to actually load.
  }
}
```

It is less than ideal since it needs an arbitrary amount of time, in this example 250 ms, to wait for the loading of the actual svg.

If you need to manipulate the svg, then you should consider using the svg as the actual template as explained here: [SVG as templates](https://angular.io/guide/svg-in-templates).

**Comment by lhf552004** [comment]
Thanks, your solution works. SVG as templates cannot be suitable for my project, as the svg is dynamic loaded.
