### ISSUE TITLE
Support for Angular 14

### ISSUE THREAD

**Issue by kuncevic** [czeckd/angular-svg-icon#141]
Not compatible with Angular 14

**Comment by czeckd** [comment]
I was able to add this package to a new ng14 project and it ran without issue. Please provide me more details on what is incompatible with angular-svg-icon@13.0.0 and Angular 14, so I can resolved it before I bump the version. Thanks!

**Comment by kuncevic** [comment]
@czeckd yeah it seems working if I use `--force` flag, the app builds, no errors, just got a dependency conflict running yarn, that is all.

**Comment by czeckd** [comment]
@kuncevic Okay, then a simple version bump should take care of it. I didn't see an issue with my simple test project using npm. Thanks!

**Comment by czeckd** [comment]
@kuncevic - v14.0.0 deployed on npm.
