### ISSUE TITLE
is there anyway to import in main.ts or app.config.ts file ?

### ISSUE THREAD

**Issue by tolgatopkara** [czeckd/angular-svg-icon#148]

**Comment by tolgatopkara** [comment]
importProvidersFrom(AngularSvgIconModule.forRoot(),)
      provideHttpClient(withInterceptorsFromDi()),
      
      
      this is works fine when i reinstall the latest on npm

**Comment by czeckd** [comment]
@tolgatopkara Are you still having a problem, or can this issue be closed?

**Comment by tolgatopkara** [comment]
it can be closed, its not throwing any error when i upgrade the latest
