### ISSUE TITLE
Unable to use icons loaded via registry - src input is always required

### ISSUE THREAD

**Issue by duszek94** [czeckd/angular-svg-icon#157]
Hello,

Affected version: **angular-svg-icon@18.0.0**

In the newest version the **src** input is always marked as required in the **SvgIconComponent**
https://github.com/czeckd/angular-svg-icon/blob/master/projects/angular-svg-icon/src/lib/svg-icon.component.ts#L29

Because of that we're unable to use icons loaded via registry as mentioned in the README.md

> If svg was previously loaded via registry with name it can be used like this:
> 
> <svg-icon name="eye" [svgStyle]="{ 'width.px':90 }"></svg-icon>

When we try to do that, the compiler throws an error and the build fails:

> NG8008: Required input 'src' from component SvgIconComponent must be specified.

Is there any workaround for that?

Thank you in advance for your help!

**Comment by czeckd** [comment]
@duszek94 Thanks for the bug report. I fixed the issue. Please grab version 18.0.1 to resolve it on your end.

**Comment by duszek94** [comment]
@czeckd I can confirm it works correctly now, thank you for the quick fix!
