### ISSUE TITLE
Support Angular 19 & Remove deprecated `allowSignalWrites` in effects

### ISSUE THREAD

**Issue by iRoyPeleg** [czeckd/angular-svg-icon#163]
Hey,

Angular 19 just dropped, and upgrading to it, now blasts with a deprecation warning regarding the need to remove `{allowSignalWrites: true}` in effects.

Waiting for an updated version.

Thanks!

**Comment by czeckd** [comment]
@iRoyPeleg - I built a simple ng19 app using angular-svg-icon@18.0.2 and didn't see any warning. I will be updating the library to ng19, but wondering if the deprecation warning is specific to your app? If not, could you provide steps to reproduce it? Thanks.

**Comment by iRoyPeleg** [comment]
Hi,

I'm not currently available for a reproduction, but the offender lies in `svg-icon.component.ts`:
```
effect(() => {
	if (this.src() || this.name()) {
		this.destroy();
		this.init(this.src(), this.name());
	}
}, {allowSignalWrites: true});
```
Since this [PR in angular v19](https://github.com/angular/angular/pull/57874), the `allowSignalWrites` is deprecated (It's enabled by default and adding that flag does nothing), and in every component that I have the uses an icon, I'm getting a console warning.

I find it weird that you dont see this warning on an ng19 app, as this is part of the core in angular.
Are you sure you're not filtering out warnings?

Thanks!

**Comment by czeckd** [comment]
Ahh, thanks for the clarification. See it now in the console. I was looking at the build. Thanks!

**Comment by czeckd** [comment]
@iRoyPeleg Package released updated for ng19. Thank you for your help!
