### ISSUE TITLE
Aren't able to set style for the svg

### ISSUE THREAD

**Issue by IvRRimum** [czeckd/angular-svg-icon#24]
Hey,

Thanks for the awesome lib!
But i ran in to an issue, when trying to style my svg's.

This is how i render it in my template:
```
        <div class="star-icon">
          <svg-icon src="/images/v2/YouRa%20vector%20icon/ic_grade_black_48px.svg" style="width: 27px;"></svg-icon>
        </div>
```

This is my css:
```
.star-icon {
  width: 27px;
  fill: #9B9B9B !important;
}
```
None of these approaches lets me edit style of my svg's.

I am on newest angular, etc.
Any ideas?

**Comment by IvRRimum** [comment]
hmm... If i put the styling in inline css it works, as soon as i add it to my components css file it doesn't work anymore ://

**Comment by czeckd** [comment]
Can share your svg please? I'll take a look at what is going on.

**Comment by ProfitWarning** [comment]
Hi,
if you want to style the markup of the svg like changing a path's fill color e.g you use it in a template of another component, you need to use something like this
`.star-icon {
  /deep/ path {
    fill: #9b9b9b;
  }
}`
but `/deep/` is deprecated? I think` ::ng-deep` is the alternative?
https://angular.io/guide/component-styles
https://github.com/angular/angular/issues/17867

**Comment by IvRRimum** [comment]
Created global.css file and included straight into index.html

That way the svg's work.

**Comment by FredUK** [comment]
I don't think creating a global.css file is a good solution or helpful at all. 

One example - and my use case - is if your fill color or any other css property is dynamic.. 

At the moment the `<svg>` tag is a child of the `<svg-icon>` component so setting any CSS on the component itself by doing `<svg-icon [ngStyle]="{'fill': getIconColor()}" src="..."` is useless as it won't travel down to the `<svg>` element.

I think the `<svg-icon>` component should by default pass all the style properties to the `<svg>` element itself as that's the most useful thing.

If passing the `ngStyle` properties down to the svg element is bad practice or unachievable we could always do a different property name such as `<svg-icon [svgStyle]="....>`
