### ISSUE TITLE
Dynamically changing src not detected

### ISSUE THREAD

**Issue by IvRRimum** [czeckd/angular-svg-icon#26]
```
          <svg-icon 
            [src]="test" 
            [class]="buttonIconsByComType[currentRoomCommunicationType][currentButtonState]['class']"></svg-icon>
```

in .ts
```
test = "/images/path.jpg"

public onclickevent() {
this.test = "/images/other_path.jpg"
}
```

Even tho onclick event is fired, the new SVG is not loading/working..

**Comment by IvRRimum** [comment]
Just tryed to clone this repo and make a build.. It ain't work that way either..

**Comment by ProfitWarning** [comment]
`"/images/path.jpg"`
Are you trying to load a jpg? Only svg images can be loaded.

**Comment by czeckd** [comment]
I see the issue. I'll make a new release to handle your use case.

**Comment by czeckd** [comment]
Added code to support `ngOnChanges` to detect when the `src` is changed.

Version 4.2.5 has this change in it.

**Comment by IvRRimum** [comment]
Works like a charm, thank you!
