### ISSUE TITLE
Angular 5 peer dependency?

### ISSUE THREAD

**Issue by HerrEmil** [czeckd/angular-svg-icon#30]
Could ` || ^5.0.0` be added to the `@angular/core` and `@angular/http` peer dependencies?

**Comment by czeckd** [comment]
Yes!

**Comment by czeckd** [comment]
Added the ng5 peer dependencies in v4.2.6. I'll switch from Http to HttpClient in v5.0.0 in a few days. Thanks.

**Comment by HerrEmil** [comment]
Awesome :)

**Comment by czeckd** [comment]
v5.0.0 is out with HttpClient.
