### ISSUE TITLE
src not accepting absolute paths?

### ISSUE THREAD

**Issue by rafaelbiten** [czeckd/angular-svg-icon#35]
Update: Yes, I was doing something wrong, so please ignore this one...

First of all, thanks for the nice module!

Now, I just updated `angular-svg-icon` to the latest version and now some of my svg icons won't load anymore because their src are absolute paths and `angular-svg-icon` is prepending the root of the project to it.

Am I doing something wrong?
Tks!

**Comment by TeodorKolev** [comment]
Why
```
<svg-icon [src]="'http://my-server/api/100.svg'"></svg-icon>
<svg-icon [src]="'https://upload.wikimedia.org/wikipedia/commons/5/53/Google_%22G%22_Logo.svg'"></svg-icon>
```
First one not working but second one works?

**Comment by czeckd** [comment]
No idea, but possibly because http://my-server cannot be found.
