### ISSUE TITLE
Mouseover alt text

### ISSUE THREAD

**Issue by laura-richer** [czeckd/angular-svg-icon#36]
When you mouse over the SVG icon the alt text reads `combined shape` is there any way to override this?

**Comment by czeckd** [comment]
I've not been able to reproduce this. Can you provide a svg that is doing this and state which browser you are using to see this?

**Comment by laura-richer** [comment]
Hi, sorry, yeah its in Chrome and I am implementing the svg as follows... 
`<svg-icon src="./assets/img/icons/compass.svg" am-compass="icon"></svg-icon>`

**Comment by czeckd** [comment]
I'm not seeing this in Chrome with the SVGs I have at hand unless it has a title element in it. Does the "compass.svg" possibly have in it?
```html
<title>combined shape</title>
```
Could you post the source for compass.svg?
