### ISSUE TITLE
Setting (dynamic) styles on SVG is not possible

### ISSUE THREAD

**Issue by FredUK** [czeckd/angular-svg-icon#40]
After encountering the same issue as #24 I was going to reply on it why I think the solution given is not the best but the issue was closed so I thought of creating a new one.

I don't think creating a global.css file is a good solution or helpful at all.

One example - and my use case - is if your fill color or any other css property is dynamic..

At the moment the `<svg>` tag is a child of the `<svg-icon>` component so setting any CSS on the component itself by doing `<svg-icon [ngStyle]="{'fill': getIconColor()}" src="..."` is useless as it won't travel down to the `<svg>` element.

I think the `<svg-icon>` component should by default pass all the style properties to the `<svg>` element itself as that's the most useful thing.

If passing the `ngStyle` properties down to the `svg` element is bad practice or unachievable we could always do a different property name such as `<svg-icon [svgStyle]="....">`

**Comment by czeckd** [comment]
Could you provide an example svg that you are seeing with this problem please? I have not been able to duplicate it. I am using `ngStyle` in the demo.

**Comment by czeckd** [comment]
I am just not seeing the issue you are seeing. Please provide an example svg where ngStyle is not working.

Here is a [StackBlitz example](https://stackblitz.com/edit/angular-bwcbzn) of the fill color changing with `[ngStyle]`. 

My component's code:
```typescript
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  private colors = [
    'Red', 'Pink', 'Purple', 'Deep Purple',
    'Indigo', 'Blue', 'Light Blue', 'Cyan', 
    'Aqua', 'Teal', 'Green', 'Light Green', 
    'Lime', 'Sand', 'Khaki', 'Yellow', 'Amber', 
    'Orange', 'Deep Orange', 'Blue Gray', 'Brown', 
    'Light Gray', 'Gray', 'Dark Gray', 'Pale Red', 
    'Pale Yellow', 'Pale Green', 'Pale-Blue'
  ];
  
  myColor = '';

  ngOnInit() {
    setInterval( () => {
      this.myColor = this.getIconColor();
    }, 1000);
  }

  randomNumber(min:number, max:number) {
      return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  getIconColor() {
    const max = this.colors.length - 1;
    const idx = this.randomNumber(0, max);
    return this.colors[idx];
  }
}
```
My component's template:
```html

<svg-icon
  src="https://raw.githubusercontent.com/czeckd/angular-svg-icon/master/images/moon-o.svg" 
  [ngStyle]="{ fill : getIconColor(), width: '90px' }" ></svg-icon>

<svg-icon
  src="https://raw.githubusercontent.com/czeckd/angular-svg-icon/master/images/eye.svg" 
  [ngStyle]="{ fill : myColor, width: '90px' }" ></svg-icon>
```

**Comment by czeckd** [comment]
Seems like the most straightforward to the #29 issue is to use @FredUK idea for `[svgStyle]` and go with that.

**Comment by czeckd** [comment]
Added `[svgStyle]` to set styles directly on the svg.

**Comment by umutdeveloper** [comment]
If SVG file has fill attribute at path tag, this attribute is not working when we set fill property on [svgStyle] because this attribute is adding fill attribute only to svg tag. But svg file has another fill propert on path tag in svg tag. 

![image](https://user-images.githubusercontent.com/20699694/60035108-bf57e900-96b4-11e9-9888-0de4e6583aa5.png)
