### ISSUE TITLE
Not working with MeInMemoryWebApiModule

### ISSUE THREAD

**Issue by ravimail26** [czeckd/angular-svg-icon#48]
In development, i am using in memory db to simulate api's. But the svg-icon stopped working saying image not found in assets folder. This woks fine when using only httpclientmodule
![screenshot_2018-05-19_11-30-02](https://user-images.githubusercontent.com/17427714/40265540-022b67fa-5b58-11e8-9164-7432944031a8.png)

**Comment by czeckd** [comment]
It seems to be related to this issue https://github.com/angular/in-memory-web-api/issues/195 with in-memory-web-api. Maybe create a reproducer and open an issue with that project?
