### ISSUE TITLE
How can I add a title to the svg?

### ISSUE THREAD

**Issue by cameronolivier** [czeckd/angular-svg-icon#50]
I'm attempting to add a contextual title for the icon.
eg, using an eye.svg I'd like the title to be "View Item", but hovering over the icon displays 'eye'. I've attempting adding a 'title' attribute to the svg but it seems it's ignored. Is there a prescribed way to do this, I'm not seeing it in the docs.

**Comment by czeckd** [comment]
I'm surprised you're seeing even 'eye' hovering over the svg. What browser/OS is doing that?

I've always just used a tooltip from Bootstrap or Material on the svg-icon. Here's an example from some code I've done this with use Angular Material's tooltip:

```html
<svg-icon [src]="nav.image" [matTooltip]="nav.hint" matTooltipPosition="right"></svg-icon>
```

**Comment by cameronolivier** [comment]
Ha that's so strange - It was in Chrome. I'll give that a look - that might be a decent way to go about it - thanks for the suggestion.

**Comment by cameronolivier** [comment]
I figured it out - there was a title tag in the SVG file we got from design...

**Comment by tdetugny** [comment]
Why did you close the thread? 
Is it possible to update the title of the svg? Adding a tooltip does not solve the problem because the title tag is still present. Is it possible to fix this?
