### ISSUE TITLE
path for images

### ISSUE THREAD

**Issue by nicolas-suhner** [czeckd/angular-svg-icon#54]
I'm trying to implement it, with a relative path to my images but it's not working. Can anyone explain me from where does the path starts?

**Comment by freezy** [comment]
How did you solve it?

**Comment by nicolas-suhner** [comment]
@freezy I added all images I got to the svgRegistry. After that, it worked.

**Comment by freezy** [comment]
I'm getting

    ERROR No svg with name 'help' has been loaded

when doing that. In `AppComponent`:

```ts
this.iconReg.loadSvg('/assets/icons/help.svg', 'help');
```

I've also tried relative paths with the same result.

**Comment by nicolas-suhner** [comment]
load the svgs to the registry
`constructor(
   private svgRegistry: SvgIconRegistryService
) {
   let iconNames = [name of the icons];
   iconNames.foreach(iconName => {
      svgRegistry.loadSvg(´{path_to_images}${iconname}.svg)
   });
}`

**Comment by freezy** [comment]
Yes, but it looks like that `path_to_images` must be an absoulte URL, not just a path (absolute or relative).

**Comment by nicolas-suhner** [comment]
my path_to_images is relative

**Comment by freezy** [comment]
Well, I load it in `AppComponent`'s `onInit()` with a path relative from `app.component.ts` to the icon, and I'm getting the error mentioned above.

**Comment by do-diegoortiz** [comment]
I could make it work either 😓 
Also, I want to get the icons from a package like `@source/some-icon-package` but I didn't find a way to tell the SvgIconRegistryService the path I want.

**Comment by czeckd** [comment]
@do-diegoortiz : You'll want to review the Angular docs for [Project asset configuration](https://angular.io/guide/workspace-config#project-asset-configuration). 

For example, here is how you could use [evil-icons package](https://www.npmjs.com/package/evil-icons). Add this "glob" to angular.json:
```json
"assets": [
   "src/favicon.ico",
   "src/assets",
  { "glob": "**/*", "input": "./node_modules/evil-icons/assets/icons", "output": "/evil-icons/" }
],
```

Then you can use the svg icons in your template:
```html
<svg-icon src="/evil-icons/ei-eye.svg" [svgStyle]="{ 'width.px':90 }"></svg-icon>
```
