### ISSUE TITLE
Use the Observable<SVGElement> in the template (not src, not name)

### ISSUE THREAD

**Issue by johanchouquet** [czeckd/angular-svg-icon#69]
Hi,

I'm trying this library which seems very cool. The thing I'm not sure if I use it correctly, so it may not be a bug.

I'm using the library to load specific svg to display it then it my template, by using the `SvgIconRegistryService`. The methods give an `Observable<SVGElement>` which is pretty cool because it allows then to add specific attributes later on such as `preserveAspectRatio` for example.

My issue is that when i try at this point to use my `svg$`, there is no method in the library to use the modified svg in the template with something like `<svg-icon name=...>` or `<svg-icon src=...`.

My use case is a bit special, because ideally, i may have to change `viewBox` by giving an offset for x & y, or the `preserveAspectRatio` according to the orientation (landscape & portrait mode) + load different svgs. So, basically, I would need a way to use the `Observable<SVGElement>` that the methods give, for example with:
`<svg-icon [src]="(mySvg$ | async)"></svg-icon>` or 
`<svg-icon [name]="(mySvg$ | async)"></svg-icon>` or 

Maybe it is very straitforward, if so, please, share :)!

Thanks

**Comment by czeckd** [comment]
I am not sure I understand what you are trying to accomplish, but could you do something with the combination of `getSvgByName(name: string) : Observable<SVGElement>` and then modify the SVG in code and then add the modified SVG to the registry with `addSvg(name: string, data: string)`? 

If you needed to add it back with the same name, you could `unloadSvg(url: string)` before adding it back?

**Comment by johanchouquet** [comment]
Thanks for your reply @czeckd .

How can i call the `getSvgByName` method if i don't load already the svg in the registry, setting a name ? If I do so, the registry would already have the svg right ? And if so, wouldn't the svg be rendered in the view ?

By reading your answer, I feel that what i would need is a method like `loadSvg(url, name)` which does not write anything in the registry. Then, calling a specific method to do so when finished tuning our svg would be do the trick, and then i would be able to use it in my template.

**Comment by czeckd** [comment]
Maybe this would be cleaner? No need to `getSvgByName` until you add the tailored SVG into the registry.

Use `addSvg(name: string, data: string)` to put the tailored SVG into the registry bypassing using the component to load the SVG. So first tune your svg, then add it to the registry.

```typescript
import { Component } from '@angular/core';
import { SvgIconRegistryService } from 'angular-svg-icon';

@Component({
  selector: 'hello',
  template: `<div><svg-icon name="box"></svg-icon></div>
            <div *ngIf="showSecond"><svg-icon name="box"></svg-icon></div>`,
  styles: []
})
export class HelloComponent {
  private serializer = new XMLSerializer();
  showSecond = false;

  constructor(private iconReg: SvgIconRegistryService) {
    this.iconReg.addSvg('box',
      `<svg xmlns="http://www.w3.org/2000/svg" style="fill:green;width:100px;"
          viewBox="0 0 10 10">
        <path d="M1 1 L1 9 L9 9 L9 1 Z"/>
      </svg>`);

    setTimeout(() => {
      this.iconReg.getSvgByName('box').subscribe(svg => {
        svg.setAttribute('style', 'fill:purple;width:50px;');
        this.iconReg.unloadSvg('box');

        const s = this.serializer.serializeToString(svg);
        console.log(s);
        this.iconReg.addSvg('box', s);
        this.showSecond = true;
      });
    }, 3000);
  }
}
```
If you need to readjust the SVG, remove it from the registry (`this.iconReg.unloadSvg('box')`). Tune it, then add it back.

This way you only add to the registry when you've tuned the SVG to what you need it to be. Need to change, then get it, modify it, unload it, and add the changed SVG back to the registry.

**Comment by johanchouquet** [comment]
That would probably do what i need indeed @czeckd ! Thanks for this. I'll try that approach very soon.

Only question that comes to me: my svg is contained in a file.
How to convert it to a simple string so that i can be able to use the `addSvg(name, data)` method ? I saw that you have a `svg-loader` file that you use. Is it OK to use it just like that ? If we take as an example the repo `angular/material2`, they use quite a lot the built-in `DomSanitizer, SafeResourceUrl`. Why don't you do the same. Does the application becomes less secure if we don't use those ?

**Comment by czeckd** [comment]
See #126 for security follow-up.
