### ISSUE TITLE
CSS is getting added to head tag, causes layout issue

### ISSUE THREAD

**Issue by nrane13** [czeckd/angular-svg-icon#71]
Description
On use of angular SVG icon, CSS is getting added in head tag like  “<style>[_nghost-c] { display: inline-block; }</style>” .
This css gets applied to the component which cause layout issue.

Environment
Angular Version: 7.2.0

**Comment by vaindil** [comment]
I have this same issue and it's driving me crazy. I'm guessing it's being added by [this code](https://github.com/czeckd/angular-svg-icon/blob/master/lib/src/svg-icon.component.ts#L12), but it really needs to not be there.

**Comment by czeckd** [comment]
@nrane13, @vaindil A reproducing example in [StackBlitz](https://stackblitz.com/) would be helpful to understand the issue you are seeing.

**Comment by vaindil** [comment]
@czeckd You can see it on [the library's demo page](https://czeckd.github.io/angular-svg-icon/). Inspect any of the `<svg-icon>` elements:
![image](https://user-images.githubusercontent.com/771134/56617859-efb8d380-65ee-11e9-9097-bacd34b7fe45.png)

**Comment by czeckd** [comment]
Ahh, that. Yes, the inline-block style was put there intentionally for the app I was originally using svg-icon for.

For now, could you do something like this in your app's styles to override it?
```css
svg-icon {
  display: unset;
}
```
I'll do some research to see how big of an impact it'll be on some of the apps I support to remove it from the component. I doubt it will be much since the display could also be set manually the same way, of it were removed from the component's style.

**Comment by czeckd** [comment]
This should now be part of angular-svg-icon@7.2.1.

**Comment by benoitjchevalier** [comment]
Nice, thank you!

Just as an FYI this had some rather unexpected implication, namely angular doesn't seem to be dealing with `:host` correctly in the context of web components. In our case we are bundling some angular component as angular elements (web components). Those elements are then consumed by other angular app.

In this scenario our angular element was still appending the inline-block style in the **head** of the page with a `_nghost-cX` selector. Then the consuming angular application would also use the `_nghost-cX` for another component, ending up messing the style of this unrelated component.

Maybe that'll help someone one day :)
