### ISSUE TITLE
Not support MS Edge browser

### ISSUE THREAD

**Issue by lxdonge** [czeckd/angular-svg-icon#74]
I try this in Edge it just shows a black block but not the svg image. I don't why this doesn't support Edge.

**Comment by lxdonge** [comment]
If I remove ng-reflect-svg-style="[object Object]" from the built html ,  the svg shows.

**Comment by czeckd** [comment]
I'm viewing the [demo](http://czeckd.github.io/angular-svg-icon/) in Microsoft Edge 41.16299.1004.0 and it shows the svgs correctly. Can you please provide a sample SVG, relevant styles, and an example how you're using it in the template?

**Comment by lxdonge** [comment]
I just use this line:
'<svg-icon src="../assets/ttt.svg" [svgStyle]="{ 'width.px':90 }"></svg-icon>' in the tmeplate.

The svg file text is :
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 104 104"><defs><style>.a{fill:#316cde;}.b{fill:#fff;}</style></defs><title>logo_vantage_L_about</title><rect class="a" width="104" height="104"/><polygon class="b" points="70.06 65.9 45.08 65.9 45.08 23.99 33.94 23.99 33.94 75.99 70.06 75.99 70.06 65.9"/></svg>`

And I have imported both  AngularSvgIconModule and HttpClientModule in the app.module.ts
Here is the simple I test:
https://drive.google.com/file/d/1SFy8HTTQEc2JnPi9qilXV4RO45KanXOd/view?usp=sharing

**Comment by czeckd** [comment]
It looks like Edge is having an issue with mixing style and classes inside an svg using the svg-icon component. For example, it works if I change the svg to be:
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 104 104">
<rect style="fill:#316cde;" width="104" height="104"/>
<polygon style="fill:#fff;" points="70.06 65.9 45.08 65.9 45.08 23.99 33.94 23.99 33.94 75.99 70.06 75.99 70.06 65.9"/>
</svg>
```
and keep the template as:
```html
<svg-icon src="../assets/ttt.svg" [svgStyle]="{ 'width.px':90 }"></svg-icon>
```
What appears to be happening is the svgStyle is overriding the internal classes and thus Edge displays it without the colors. If you comment out the rect in the svg, it will just display the polygon in black & white.

Even enclosing the original svg in a div seems to cause the problem in Edge:
```html
<div style="width:90px">
    <svg-icon src="../assets/ttt.svg"></svg-icon> 
</div>
```
Not sure what the best approach to take to resolve this in Edge.

**Comment by lxdonge** [comment]
I got it，thanks anyway.

**Comment by radulescuandrew** [comment]
Still happening. Anything from last year?

**Comment by czeckd** [comment]
@radulescuandrew: 

The `<svg-icon>` appears to working when I tested it with Microsoft Edge 83.0.478.45 (Official build) (64-bit). 

Here's a [stackblitz](https://stackblitz.com/edit/angular-ivy-gvpr3e?file=src%2Fapp%2Fapp.component.html).
