### ISSUE TITLE
src attribute in <svg-icon> is not bindable

### ISSUE THREAD

**Issue by mueedahmed1** [czeckd/angular-svg-icon#75]
### `<svg-icon` `src="../../../../../assets/images/{{i.name}}.svg"></svg-icon>` @czeckd

**Comment by Vienyame** [comment]
Hello ,
Pls try this:
`const mySvgPath = "../../../../../assets/images/{{i.name}}.svg"`

and in your template use::
`<svg-icon [src]="mySvgPath "></svg-icon>`

Regards
