### ISSUE TITLE
Can't bind to 'svgStyle' since it isn't a known property of 'svg-icon'.

### ISSUE THREAD

**Issue by Epsilon-Rashmi** [czeckd/angular-svg-icon#77]
Getting this error.

1. If 'svg-icon' is an Angular component and it has 'svgStyle' input, then verify that it is part of this module.
2. If 'svg-icon' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.

 I am using Angular 7.2.0 version.

**Comment by Supratentorial** [comment]
That just looks like you either haven't installed via npm, or haven't included the AngularSvgIconModule import in the relevant module.

**Comment by vimalvr** [comment]
@Epsilon-Rashmi I also faced the same issue and included in the relavent module and it's working fine. 

@Supratentorial thank you :)
