### ISSUE TITLE
SVG icons doesn't render properly on Safari

### ISSUE THREAD

**Issue by ranmedina** [czeckd/angular-svg-icon#80]
Hello,

Is it possible that this library does not support Safari?
SVG icons are rendering perfectly on every browser, but when I view it using my iPhone, the SVG icon becomes black & white.

However, using:
`<img src="icon.svg">`
works.

Example:
 <svg-icon src='assets/images/iostest.svg'></svg-icon>
Chrome:
![chrome](https://user-images.githubusercontent.com/36334461/62725500-e75d9a80-ba1d-11e9-9cdc-d51d8860eb93.png)
Safari:
<img width="111" alt="ios" src="https://user-images.githubusercontent.com/36334461/62725501-e75d9a80-ba1d-11e9-9b91-0bee5937783a.png">

Any ideas?

**Comment by czeckd** [comment]
@jayzienS If you open just the SVG file in Safari outside of Angular, does it display the shading? It may be an issue with the SVG for Safari than the library. The library looks like it is displaying the SVG, just not the shading. 

Please attach the SVG if you want further help.

**Comment by ranmedina** [comment]
> @jayzienS If you open just the SVG file in Safari outside of Angular, does it display the shading? It may be an issue with the SVG for Safari than the library. The library looks like it is displaying the SVG, just not the shading.
> 
> Please attach the SVG if you want further help.

Yeah, I just ran a test on a local server using the `<svg>` element and it seems like displaying the SVG on a blank page outside the framework works properly.
Any idea what the issue could be?

There is the SVG file -
[iostestsvg.zip](https://github.com/czeckd/angular-svg-icon/files/3485518/iostestsvg.zip)
or
https://pastebin.com/sihnB0Nk

**Comment by czeckd** [comment]
I've not been able to reproduce this. I just added use of your icon to the library's demo app for my test. I loaded the SVG using the library without any issue with Safari on a MacOS desktop, iPad, and iPhone. Here it is on Safari on an iPhone:
![IMG_4727](https://user-images.githubusercontent.com/17859320/62792983-56220e80-ba85-11e9-9773-b88c351d5bf9.PNG)
This is the HTML I used:

```html
<div>
    <svg-icon src="images/testicon1.svg"></svg-icon>
</div>
```
Maybe there is a style in your app that is interfering with it?

**Comment by czeckd** [comment]
Ahh, I just noticed you're not using the library in your example. You are loading it with the `<img>` tag not the `<svg-icon>` tag that is from the library.

**Comment by ranmedina** [comment]
> I've not been able to reproduce this. I just added use of your icon to the library's demo app for my test. I loaded the SVG using the library without any issue with Safari on a MacOS desktop, iPad, and iPhone. Here it is on Safari on an iPhone:
> ![IMG_4727](https://user-images.githubusercontent.com/17859320/62792983-56220e80-ba85-11e9-9773-b88c351d5bf9.PNG)
> This is the HTML I used:
> 
> ```
> <div>
>     <svg-icon src="images/testicon1.svg"></svg-icon>
> </div>
> ```
> 
> Maybe there is a style in your app that is interfering with it?



> Ahh, I just noticed you're not using the library in your example. You are loading it with the `<img>` tag not the `<svg-icon>` tag that is from the library.

I gave the `<img>` element as a working example, when I use `<svg-icon>` it doesn't work unfortunately.
However, I ran a test on a fresh angular app using your library and indeed it renders properly, which leads me to the conclusion that something in my app is interfering.

I will do some deep researching into this, thanks for your assistance anyway!
