### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by devendradatatech** [czeckd/angular-svg-icon#82]
Hello,
I had used this NPM for SVG its working fine while I take SVG from the assets/image.

But when I take it from the API it blocks by the angular.
I had also allowed cross-browser in the header.
`header('Access-Control-Allow-Origin: *'); `
I got below issue please look into it and if any solution for that please let me know.

**Access to XMLHttpRequest at 'http://localhost/2019/project/admin/media/services/truck_green%20(2).svg' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.**

**Comment by czeckd** [comment]
You're running your app on localhost:4200 and you're trying to read content from localhost port 80. That is why you're running into a CORS issue. You will need to set the CORS headers to work with your app on localhost. This has nothing to do with this package.

**Comment by gopal-augment** [comment]
I'm facing the same issue. But how it is working in the <img> tag?

**Comment by gopal-augment** [comment]
> You're running your app on localhost:4200 and you're trying to read content from localhost port 80. That is why you're running into a CORS issue. You will need to set the CORS headers to work with your app on localhost. This has nothing to do with this package.

[](https://github.com/czeckd/angular-svg-icon/issues/82)I'm facing the same issue. But how it is working in the img tag?

**Comment by skrzepij** [comment]
Have same issue with Angular 17 and angular-svg-icon@17
With `<img />` tag, images from the server works like a charm. 
But when I try to use `<svg-icon [src]="iconSrc"  />` instead, I got an  `No 'Access-Control-Allow-Origin'` error. 

Configuring proxy.conf.json with: 
```js
    "secure": false,
    "logLevel": "debug",
    "changeOrigin": true
```

didn't help as well. 

@gopal-augment did you find any workaround?
