### ISSUE TITLE
angular universal 

### ISSUE THREAD

**Issue by accidentul** [czeckd/angular-svg-icon#84]
do you have an example how to use it with angular universal ?
where to put the SvgServerLoader class becouse angular nodemodules dosen't have fs module

**Comment by czeckd** [comment]
I do not have an example at hand, but maybe @freezy or @edulelis does?

**Comment by ihor-zinchenko** [comment]
any updates?)

**Comment by conradkirschner** [comment]
push

**Comment by todorpavlovic** [comment]
Updates ?

**Comment by czeckd** [comment]
@edulelis created an example project [demo-universal-angular-svg-loader](https://github.com/edulelis/demo-universal-angular-svg-loader). 

> The basic stuff to get this working is:
>
> 1. As per the suggestion [here](https://github.com/angular/angular-cli/issues/8272#issuecomment-392777980).
> Add this snippet to the `package.json` file to prevent compilation issues.
>```json
>"browser": {
>    "fs": false,
>    "path": false,
>    "os": false
>}
>```
>2. Add `ServerTransferStateModule` to `app.server.module`
>3. Add `BrowserTransferStateModule` to `app.module`
>4. The loader should be different per platform, so the factory should receive the `PLATFORM_ID` and load the  correct class appropriately (this is already added in the example).

**Comment by todorpavlovic** [comment]
Thank you so much, we have great community here !

**Comment by MickL** [comment]
Cant this be closed? There is this documentation: https://github.com/czeckd/angular-svg-icon#usage-with-angular-universal
