### ISSUE TITLE
Add viewbox attribute

### ISSUE THREAD

**Issue by AsafAgranat** [czeckd/angular-svg-icon#85]
Please add `viewbox` attribute to the SVG element, and allow to pass it as an optional @Input. Without `viewbox` SVGs don't scale along with their parent container, but remain fixed to their defines width/height.

**Comment by czeckd** [comment]
I think it is be better to fix the SVG to have a viewbox set before use than do it programatically. What's your use case for using SVGs without a viewbox and then setting it through the component?

**Comment by AsafAgranat** [comment]
`viewbox` allows defining the SVG width/height of 100%, which allows it to grow/shrink according to it's container. Without `viewbox` the SVG takes on whatever unit size is defined explicitly.

I've prepared a [Codepen example](https://codepen.io/rhmubus/pen/YzKdEGw)

You can always detect whether the SVG has viewbox defined already, and then use that, otherwise add a default one (according to the optional @Input())

**Comment by czeckd** [comment]
Yes, I understand what a viewbox does. What I do not understand is why you would use a SVG without one already set? It seems to me more straightforward to fix the SVG in advance of using it in an application to have the appropriate viewbox set.

So, what I am wondering is what is the use case to use SVGs without a viewbox and then fix them, by setting a viewbox with the component? If an application is planning on using a SVG that is intended to be scalable and the SVG does not have a viewbox set, then that SVG is incomplete.

**Comment by AsafAgranat** [comment]
My use case was, that i used an SVG directly from a Wikimedia URL, and that SVG rendered without a viewbox attribute. Not having an intermediary method to include the viewbox, i had to resolve to either download the file first, or apply an attribute on runtime, both of which solution defeat the purpose of having a convenient library to do it, in my opinion.

**Comment by czeckd** [comment]
@AsafAgranat I have a viewBox attribute working in a branch, but adding a viewBox may not be as useful when the height and width attributes are still set on the SVG. What are your thoughts on automatically removing the height and width attributes on the svg if the svg-icon has a viewBox set?

**Comment by bladeski** [comment]
I have another use-case for this, whereby I use the same SVG icon in numerous places on my app, but in some places I wish to specify the viewbox in order to crop part of the image. It may be that my understanding of how the viewbox works is incorrect, or that there may be another way to approach this issue, however my initial investigation into this suggests that it is probably the most straight-forward way.

**Comment by czeckd** [comment]
@AsafAgranat, @bladeski angular-svg-icon@9.1.0 now has a means to set the viewBox. Here's the documentation from the readme:

> [viewBox] - An optional string to set the viewBox on the SVG. If the viewBox="auto", then svg-icon will attempt to convert the SVG's width and height attributes to a viewBox="0 0 w h". Both explicitly setting the viewBox or auto setting the viewBox will remove the SVG's width and height attributes.
