### ISSUE TITLE
Using different SVG's but loading the same one

### ISSUE THREAD

**Issue by pachidev** [czeckd/angular-svg-icon#89]
I'm loading 4 different SVG icons dynamically in the component constructor.
![image](https://user-images.githubusercontent.com/47981758/69059319-8e86a080-0a15-11ea-917f-9714cb43dc27.png)

When I use them in the HTML the first one is the only well rendered.

In this example, I set those four and right after I put the same ones but using an <img> tag:
![image](https://user-images.githubusercontent.com/47981758/69059438-d0174b80-0a15-11ea-9999-3a86866f3d4f.png)

The result is:
![image](https://user-images.githubusercontent.com/47981758/69059540-06ed6180-0a16-11ea-82ab-12ffcbff8b86.png)

**Comment by czeckd** [comment]
I've not been able to reproduce this. In the demo app, what I've done:

```ts
  constructor(private registry: SvgIconRegistryService) {
    this.registry.loadSvg('assets/images/eye.svg', 'eye.icn');
    this.registry.loadSvg('assets/images/moon-o.svg', 'moon.icn');
  }
```
And in the template:
```html
<div class="portal">
    <svg-icon name="eye.icn"></svg-icon>
    <svg-icon name="moon.icn"></svg-icon>
</div>
```

And both the eye svg and moon svg load as expected.

**Comment by pachidev** [comment]
I found the problem. All the SVGs I was provided have the same ids (they're around 50):

![image](https://user-images.githubusercontent.com/47981758/69127426-83318480-0aaa-11ea-8d18-e333da64aa3d.png)

So the problem is when trying to load multiple ones with the same ID. 
Not sure if it's your business though 😅
Thank you 👍
