### ISSUE TITLE
Multiple registry services in cause of unnecessary provider in module

### ISSUE THREAD

**Issue by Adam-Michalski** [czeckd/angular-svg-icon#92]
Every place where you import module there is provider injected `SVG_ICON_REGISTRY_PROVIDER`.
It should be only provided as already is in forRoot method.

This issue causes multiple SvgIconRegistryService instances for lazy loaded modules and other complications for non lazy modules.

**Comment by czeckd** [comment]
@Adam-Michalski - if you have a fix, please make a pull request.

**Comment by czeckd** [comment]
@Adam-Michalski:  After more testing, I believe this is working as expected.

If you are lazy loading modules, then import AngularSvgIconModule only in the AppModule. Do not import the module in the lazily-loaded child modules. 

I will add a throw in the constructor if the module is already loaded.

**Comment by czeckd** [comment]
@Adam-Michalski: I think I see what problem you uncovered. I am going to change the module in version 9.0.0 to require that an explicit forRoot() call be made if the providers are wanted.
