### ISSUE TITLE
Ng build on Angular 8 not working in 9.1.0 version

### ISSUE THREAD

**Issue by wilianx7** [czeckd/angular-svg-icon#97]
Hello,

I updated the version of ```angular-svg-icon``` to ```9.1.0``` and after this procedure my project pointed out some errors in the console when running ```ng build```, making it not possible to compile.

Previously I was using version ```8.0.0``` and the ```ng build``` worked correctly.

![image](https://user-images.githubusercontent.com/42422976/76090839-0fed4900-5f9b-11ea-8bf9-e4c3651a32ec.png)

**Comment by czeckd** [comment]
@wilianx7 - Hi, what version of Angular and rxjs are you using? I'm trying to reproduce this.

**Comment by wilianx7** [comment]
@czeckd - I'm using rxjs 6.4.0 and Angular 8.2

**Comment by czeckd** [comment]
@wilianx7 - Ahh that's the problem. the angular-svg-icon@9.x versions are for Angular 9.x and later (as it says in the [README](https://github.com/czeckd/angular-svg-icon/blob/master/README.md)). You'll need to ng update your project to 9.x to use the latest version of angular-svg-icon.
